name "Hello World"
inputs:
  who-to-greet:
    description: "blah"
    required: true
    default: "World"
outputs:
  time:
    description: "blah"
runs:
  using: "docker"
  image "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
